services:

  bot:
    image: soa:latest
    depends_on:
      - postgres
    volumes:
      - ./:/opt/bot
    entrypoint: python bot.py
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgres:17.5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backup:/backup
    env_file:
      - ./postgresql.env
    restart: unless-stopped
    networks:
      - backend
  
  # For Development Only!
  adminer:
    profiles: ["dev-only"]
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - backend


networks:
  backend:
